### ISSUE TITLE
Check timeseries for timer step-sizes greater than 3600 seconds

### ISSUE THREAD

**Issue by ss391347** [RWTH-EBC/pyCity#276]
Right now, the resampling function only performs well on "up-sampling". At "down-scaling", as it only interpolates between the 2 closest values, undesired results are produced. For example, in the extreme, when using the step-size 86400 (=1 year) in a timer object, all values for qDirect and qDiffuse in the weather class become 0.

**Comment by sebuer** [comment]
There seems to be tests written for such cases such as https://github.com/RWTH-EBC/pyCity/blob/7a3ddbae2f3721d4c0d6d47ce4e4cbdcab26239b/pycity_base/test/test_change_resolution.py#L13-L19

and when looking at the function `changeResolution` it seems to performs as described in the documentation.
Thinking of the input values as measured values at sample times and also of the output values as measured values at sample times, the functions output is as described.
Since this behaviour is often undesired, I can think of the following options:

- Change `changeResolution` to only operate in sum mode. Add a new function for calculating averages from sampled values. Use the new function on data, even if the new step-size is the same as the old step size, since sampled values are being transformed to average values.
- Change `changeResolution` to only operate in sum mode. If mean mode is selected, multiply the values with `oldResolution / newResolution` after sum conversion.
- Add a warning when upsampling that results can be undesired.

@ss391347 Do you have another suggestion on how this issue can be fixed? I am aware that the first suggestions would alter many generated profiles slightly even at down-scaling. In my opinion the distinction between sampled values and mean values is currently not consistent enough. I am unsure what behaviour is desired.

**Comment by sebuer** [comment]
#287 changes `changeResolution` to use "sum" mode when downscaling even if "mean" is selected.
Maybe a transition to `scipy.interpolate.InterpolatedUnivariateSpline` could lead to better interpolation results. This would require a larger restructuring of the current code.

**Comment by ss391347** [comment]
Very good. Thank you very much @sebuer! :)
